"""user_name is changed to ununique

Revision ID: 3ba9faff2e5a
Revises: 650fd81e1d1a
Create Date: 2021-04-05 23:49:25.342017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba9faff2e5a'
down_revision = '650fd81e1d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_user_name', table_name='users')
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=False)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.create_index('ix_users_user_name', 'users', ['user_name'], unique=1)
    # ### end Alembic commands ###
