"""new column of User table -- phone

Revision ID: 650fd81e1d1a
Revises: ea3313043bf2
Create Date: 2021-04-05 23:03:44.651525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650fd81e1d1a'
down_revision = 'ea3313043bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
